name: wordhoard
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0-1.0.dev

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_ui_auth: ^1.6.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
